#!/bin/bash

# Standardwerte initialisieren
FOLDER=""
PASSWORD=""
FQDN=""
PORTNUMBER="8443"
SVWSVERSION=""

usage() {
    echo "Benutzung: $0 -o <FOLDER> -v <SVWSVERSION> [-p <PASSWORD>] [-dn <FQDN>] [-pt <PORTNUMBER>]"
    echo "  -o  Ordnerpfad (Pflichtangabe)"
    echo "  -v  SVWS Server Version (Pflichtangabe)"
    echo "  -p  Passwort (optional, sonst Autogenerierung)"
    echo "  -dn Fully Qualified Domain Name (Fallback: Ordnername)"
    echo "  -pt Portnummer (Standard: 8443)"
    exit 1
}

# Parameter verarbeiten
while [[ $# -gt 0 ]]; do
    case $1 in
        -o) FOLDER="$2"; shift 2 ;;
        -v) SVWSVERSION="$2"; shift 2 ;;
        -p) PASSWORD="$2"; shift 2 ;;
        -dn) FQDN="$2"; shift 2 ;;
        -pt) PORTNUMBER="$2"; shift 2 ;;
        *) usage ;;
    esac
done

# 1. Pflichtangaben prüfen
if [[ -z "$FOLDER" ]] || [[ -z "$SVWSVERSION" ]]; then
    echo "Fehler: Die Parameter -o (FOLDER) und -v (SVWSVERSION) sind zwingend erforderlich."
    usage
fi

# 2. Port-Check
if command -v lsof >/dev/null 2>&1; then
    if lsof -Pi :"$PORTNUMBER" -sTCP:LISTEN -t >/dev/null ; then
        echo "FEHLER: Port $PORTNUMBER wird bereits verwendet!"
        exit 1
    fi
fi

# 3. Fallbacks
[[ -z "$FQDN" ]] && FQDN="$FOLDER"

if [[ -z "$PASSWORD" ]]; then
    PASSWORD=$(openssl rand -base64 12)
    IS_AUTOGENERATED=true
fi

# 4. Verzeichnisstruktur vorbereiten
mkdir -p "$FOLDER/volume/mariadb"
mkdir -p "$FOLDER/volume/svws"
# Berechtigungen sicherstellen, damit MariaDB schreiben darf
chmod -R 777 "$FOLDER/volume"

# 5. .env Datei erzeugen
cat <<EOF > "$FOLDER/.env"
IMPORT_TEST_DATA=false
MARIADB_ROOT_PASSWORD=$PASSWORD
MARIADB_HOST=mariadb
SVWS_TLS_KEYSTORE_PASSWORD=$PASSWORD
SVWS_TLS_KEY_ALIAS=svws
SVWS_TLS_KEYSTORE_PATH=.
SVWS_TLS_CERT_CN=SVWS3TESTSERVER
SVWS_TLS_CERT_OU=SVWSOU
SVWS_TLS_CERT_O=SVWSO
SVWS_TLS_CERT_L=D
SVWS_TLS_CERT_S=NRW
SVWS_TLS_CERT_C=DE
SERVERNAME=$FQDN
PORT=$PORTNUMBER
EOF

# 6. docker-compose.yml erzeugen
cat <<EOF > "$FOLDER/docker-compose.yml"
services:
  mariadb:
    restart: always
    image: mariadb:latest
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h localhost -u root -p$${MARIADB_ROOT_PASSWORD}"]
      start_period: 20s
      interval: 5s
      timeout: 5s
      retries: 3
    volumes:
      - ./volume/mariadb:/var/lib/mysql

  svws-server:
    image: svwsnrw/svws-server:$SVWSVERSION
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "$PORTNUMBER:8443"
    volumes:
      - ./volume/svws:/opt/app/svws/conf
    env_file:
      - .env
EOF

echo "------------------------------------------------"
echo "Konfiguration erstellt!"
echo "------------------------------------------------"
echo "Ordner:        $FOLDER"
echo "Externer Port: $PORTNUMBER"
echo "Passwort:      $PASSWORD"
echo "------------------------------------------------"
echo "Starten mit: cd $FOLDER && docker compose up -d"
cd $FOLDER && docker compose up -d