image: node:16
pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm run build
    - cp -a .vitepress/dist/. public/
  artifacts:
    paths:
      - public
  only:
    - main